### ISSUE TITLE
Сan't switch between pages

### ISSUE THREAD

**Issue by LSevens** [gitkv/govnotion#1]
1. Make 2 or more pages
2. Click on inactive page

Expected result: Page switched
Fact result: Page not switched

**Comment by nivolk** [comment]
Thank you for your feedback and for bringing this issue to our attention. We have identified the problem and have implemented the necessary fixes. The corrections have been applied and are available in the latest update on the master branch. We appreciate your input and encourage you to try the updated version.

Thank you for helping us improve GovNotion.

Best regards,
GovNotion Team

**Comment by kyoto540** [comment]
Best company ever
